server {
    listen 80;
    server_name localhost;

    # Корень сайта
    root /usr/share/nginx/html;
    index index.html;

    # Разрешаем обращаться напрямую к статике
    location / {
        try_files $uri $uri/ /index.html;
    }

    # CORS и заголовки
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        add_header Access-Control-Allow-Origin *;
    }

    # Простая отдача API-запросов к core-service (прокси)
    location /api/ {
        proxy_pass http://core-service:8099/;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }
}
