services:
  postgres:
    image: postgres:16-alpine
    container_name: mde-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medical"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [mednet]

  user-service:
    build:
      context: .
      dockerfile: backend/user-service/Dockerfile
    container_name: mde-user
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50053:50053"
    networks: [mednet]

  data-transfer-service:
    build:
      context: .
      dockerfile: backend/data-transfer-service/Dockerfile
    container_name: mde-dt
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50052:50052"
    networks: [mednet]

  core-service:
    build:
      context: .
      dockerfile: backend/core-service/Dockerfile
    container_name: mde-core
    depends_on:
      - user-service
      - data-transfer-service
    ports:
      - "8099:8099"
    networks: [mednet]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mde-frontend
    depends_on:
      - core-service
    ports:
      - "8080:80"
    networks: [mednet]
  info:
      image: alpine
      command: >
        sh -c "echo '🌐 Frontend доступен:  http://localhost:8080'
        && echo '🔌 Core API работает:  http://localhost:8099'
        && echo '✅ Всё готово! Можно открывать браузер 🚀'"
      depends_on:
        - frontend
      networks: [ mednet ]


volumes:
  pgdata:

networks:
  mednet:
    driver: bridge
