services:
  postgres:
    image: postgres:16-alpine
    container_name: mde-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/docker/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medical"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [mednet]

  user-service:
    build:
      context: ./backend          # 👈 контекст — папка backend
      dockerfile: user-service/Dockerfile
    container_name: mde-user
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50053:50053"
    networks: [mednet]

  data-transfer-service:
    build:
      context: ./backend
      dockerfile: data-transfer-service/Dockerfile
    container_name: mde-dt
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50052:50052"
    networks: [mednet]

  blockchain-service:
    build:
      context: ./backend
      dockerfile: blockchain-service/Dockerfile
    container_name: mde-blockchain
    environment:
      - GRPC_ADDR=:50054
      - FABRIC_CHANNEL=medical-channel
      - FABRIC_CHAINCODE=medical-access
    ports:
      - "50054:50054"
    networks: [mednet]
    volumes:
      - ./blockchain/fabric/network/crypto-config:/app/crypto:ro
      - ./blockchain/fabric/config:/app/config:ro

  core-service:
    build:
      context: ./backend
      dockerfile: core-service/Dockerfile
    container_name: mde-core
    depends_on:
      - user-service
      - data-transfer-service
      - blockchain-service
    ports:
      - "8099:8099"
    networks: [mednet]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mde-frontend
    depends_on:
      - core-service
    ports:
      - "8080:80"
    networks: [mednet]

  ganache:
    platform: linux/amd64
    image: trufflesuite/ganache-cli:latest
    container_name: mde-ganache
    command: >
      --accounts 10
      --defaultBalanceEther 1000
      --mnemonic "test test test test test test test test test test test junk"
      --gasLimit 8000000
      --port 8545
    ports:
      - "8545:8545"
    networks: [ mednet ]

  blockchain-deployer:
    build:
      context: ./backend/blockchain-contracts
    container_name: mde-blockchain-deployer
    depends_on:
      - ganache
    networks: [ mednet ]

  info:
    image: alpine
    command: >
      sh -c "echo '🌐 Frontend:  http://localhost:8080'
      && echo '🔌 Core API:  http://localhost:8099'
      && echo '✅ Всё готово! Открывай браузер 🚀'"
    depends_on:
      - frontend
    networks: [mednet]

volumes:
  pgdata:

networks:
  mednet:
    driver: bridge