server:
  port: 50052

database:
  url: "host=localhost user=postgres password=postgres dbname=MedicalDataExchange port=5432 sslmode=disable"

auth:
  jwt_secret: "supersecret"

encryption:
  secret: "your-encryption-secret-key-32-bytes-long!!!"